blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions
    url: https://github.com/thrivea/public-issue-tracker/discussions
    about: Please use GitHub Discussions for non-issue conversations
